channels:
- conda-forge
dependencies:
- python=3.9.16
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.1
  - ipython==8.10.0
  - torchmetrics==0.11.1
  - torch==1.12.1
  - torchvision==0.13.1
  - --extra-index-url https://download.pytorch.org/whl/cu113
name: mlflow-env
